/* after changing this file run 'npm run webpack:build' */
/* tslint:disable */
import '../content/scss/vendor.scss';
import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faAngleLeft,
    faAngleRight,
    faAppleAlt,
    faArrowCircleLeft,
    faArrowCircleRight,
    faArrowCircleUp,
    faArrowLeft,
    faArrowRight,
    faArrowsAlt,
    faAsterisk,
    faBan,
    faBars,
    faBell,
    faBook,
    faBookmark,
    faBookReader,
    faBullseye,
    faCalendarAlt,
    faCamera,
    faChartArea,
    faChartBar,
    faChartPie,
    faCheck,
    faCheckCircle,
    faCircle,
    faClock,
    faCloud,
    faCodeBranch,
    faDatabase,
    faDirections,
    faDotCircle,
    faDrawPolygon,
    faExclamation,
    faExclamationTriangle,
    faEye,
    faFileImport,
    faFilter,
    faFlag,
    faGlobe,
    faGripVertical,
    faHandPaper,
    faHdd,
    faHeart,
    faHome,
    faImage,
    faInfo,
    faList,
    faMagic,
    faMapMarkedAlt,
    faMapMarker,
    faMapMarkerAlt,
    faMinus,
    faNetworkWired,
    faPencilAlt,
    faPlug,
    faPlus,
    faPlusSquare,
    faRoad,
    faRssSquare,
    faSave,
    faSearch,
    faShieldAlt,
    faSignInAlt,
    faSignOutAlt,
    faSitemap,
    faSort,
    faSortDown,
    faSortUp,
    faSquare,
    faStreetView,
    faSync,
    faSyncAlt,
    faTable,
    faTachometerAlt,
    faTasks,
    faTh,
    faThList,
    faTimes,
    faToolbox,
    faTrashAlt,
    faUser,
    faUserCircle,
    faUserPlus,
    faUsers,
    faUserSecret,
    faUserTag,
    faWifi,
    faWindowMaximize,
    faWindowMinimize,
    faWrench
} from '@fortawesome/free-solid-svg-icons';
import { faArrowCircleDown } from '@fortawesome/free-solid-svg-icons/faArrowCircleDown';

// Imports all fontawesome core and solid icons

// Adds the SVG icon to the library so you can use it in your page
library.add(faUser);
library.add(faSort);
library.add(faSortUp);
library.add(faSortDown);
library.add(faSync);
library.add(faEye);
library.add(faBan);
library.add(faTimes);
library.add(faArrowLeft);
library.add(faSave);
library.add(faPlus);
library.add(faPencilAlt);
library.add(faBars);
library.add(faHome);
library.add(faThList);
library.add(faUserPlus);
library.add(faRoad);
library.add(faTachometerAlt);
library.add(faHeart);
library.add(faList);
library.add(faBell);
library.add(faTasks);
library.add(faBook);
library.add(faHdd);
library.add(faFlag);
library.add(faWrench);
library.add(faClock);
library.add(faCloud);
library.add(faSignOutAlt);
library.add(faSignInAlt);
library.add(faCalendarAlt);
library.add(faSearch);
library.add(faTrashAlt);
library.add(faAsterisk);
library.add(faChartArea);
library.add(faArrowLeft);
library.add(faArrowRight);
library.add(faGlobe);
library.add(faRssSquare);
library.add(faPlug);
library.add(faSitemap);
library.add(faCodeBranch);
library.add(faDotCircle);
library.add(faArrowsAlt);
library.add(faArrowCircleDown);
library.add(faArrowCircleUp);
library.add(faArrowCircleRight);
library.add(faArrowCircleLeft);
library.add(faHandPaper);
library.add(faBullseye);
library.add(faImage);
library.add(faUserCircle);
library.add(faAngleRight);
library.add(faAngleLeft);
library.add(faShieldAlt);
library.add(faAppleAlt);
library.add(faUserSecret);
library.add(faWifi);
library.add(faFileImport);
library.add(faCheck);
library.add(faMagic);
library.add(faCircle);
library.add(faCheckCircle);
library.add(faSquare);
library.add(faDrawPolygon);
library.add(faGripVertical);
library.add(faHandPaper);
library.add(faPencilAlt);
library.add(faMapMarkedAlt);
library.add(faChartPie);
library.add(faSyncAlt);
library.add(faChartBar);
library.add(faExclamation);
library.add(faPlusSquare);
library.add(faMapMarker);
library.add(faNetworkWired);
library.add(faBookReader);
library.add(faMinus);
library.add(faWindowMaximize);
library.add(faWindowMinimize);
library.add(faDirections);
library.add(faBookmark);
library.add(faStreetView);
library.add(faCamera);
library.add(faInfo);
library.add(faMapMarkerAlt);
library.add(faToolbox);
library.add(faUsers);
library.add(faDatabase);
library.add(faFilter);
library.add(faUserTag);
library.add(faExclamationTriangle);
library.add(faTh);
library.add(faTable);

// jhipster-needle-add-element-to-vendor - JHipster will add new menu items here
