mkdir -p /home/capgemini/binding/INSIGHT/nifi/
cp ../feeder/* /home/capgemini/binding/INSIGHT/nifi/
mkdir -p /home/capgemini/binding/INSIGHT/nifi/out
mkdir -p /home/capgemini/binding/INSIGHT/master
mkdir -p /home/capgemini/binding/INSIGHT/data
mkdir -p /home/capgemini/binding/INSIGHT/logstash/
cp ./logstash/* /home/capgemini/binding/INSIGHT/logstash/
mkdir -p /home/capgemini/binding/INSIGHT/mongodb/
mkdir -p /home/capgemini/binding/INSIGHT/graph
cp ../graph/* /home/capgemini/binding/INSIGHT/graph/