mkdir -p /home/capgemini/binding/INSIGHT/nifi/
cp ../feeder/* /home/capgemini/binding/INSIGHT/nifi/
mkdir -p /home/capgemini/binding/INSIGHT/nifi/out
mkdir -p /home/capgemini/binding/INSIGHT/master
mkdir -p /home/capgemini/binding/INSIGHT/data
mkdir -p /home/capgemini/binding/INSIGHT/elasticsearch-console
mkdir -p /home/capgemini/binding/INSIGHT/elasticsearch
mkdir -p /home/capgemini/binding/INSIGHT/logstash/
cp ./logstash/* /home/capgemini/binding/INSIGHT/logstash/
mkdir -p /home/capgemini/binding/INSIGHT/mongodb/
mkdir -p /home/capgemini/binding/INSIGHT/graph
cp ../graph/conf/* /home/capgemini/binding/INSIGHT/graph/
mkdir -p /home/capgemini/binding/INSIGHT/refgeo/logstash/
mkdir -p /home/capgemini/binding/INSIGHT/refgeo/logstash/csv
cp ../refgeo/logstash/csv/* /home/capgemini/binding/INSIGHT/refgeo/logstash/csv
mkdir -p /home/capgemini/binding/INSIGHT/refgeo/logstash/pipeline
cp ../refgeo/logstash/pipeline/* /home/capgemini/binding/INSIGHT/refgeo/logstash/pipeline
